{
  "hash": "ac4cd69f8fe3176b46a2a24e0c73088f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supplement 1\"\nsubtitle: \"Analysis of human visual experience data\"\nauthor:\n  - name: \"Johannes Zauner\"\n    id: JZ\n    affiliation: \n      - Technical University of Munich, Germany\n      - Max Planck Institute for Biological Cybernetics, Tübingen, Germany\n    orcid: \"0000-0003-2171-4566\"\n    corresponding: true\n    email: johannes.zauner@tum.de\n  - name: \"Aaron Nicholls\"\n    affiliation: \"Reality Labs Research, USA\"\n    orcid: \"0009-0001-6683-6826\"\n  - name: \"Lisa A. Ostrin\"\n    affiliation: \"University of Houston College of Optometry, USA\"\n    orcid: \"0000-0001-8675-1478\"\n  - name: \"Manuel Spitschan\"\n    affiliation: \n      - Technical University of Munich, Germany\n      - Max Planck Institute for Biological Cybernetics, Tübingen, Germany\n      - Technical University of Munich Institute of advanced study (TUM-IAS), Munich, Germany\n    orcid: \"0000-0002-8572-9268\"\ndoi: 10.5281/zenodo.16566014\nformat:\n  html:\n    toc: true\n    include-in-header:\n      - text: |\n          <style>\n          .quarto-notebook .cell-container .cell-decorator {\n            display: none;\n          }\n          </style>\n    number-sections: true\n    code-tools: true\n    html-math-method:\n      method: mathjax\n      url: \"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML\"\nbibliography: references.bib\nlightbox: true\nexecute:\n  echo: true\n  warning: false\n---\n\n## Abstract {.unnumbered}\n\nThis supplementary document provides a detailed, step-by-step tutorial on importing and preprocessing raw data from two wearable devices: `Clouclip` and `VEET`. We describe the structure of the raw datasets recorded by each device and explain how to parse these data, specify time zones, handle special sentinel values, clean missing observations, regularize timestamps to fixed intervals, and aggregate data as needed. All original R code from the [main tutorial](index.qmd) is shown here for transparency, with additional guidance intended for a broad research audience. We demonstrate how to detect gaps and irregular sampling, convert implicit missing periods into explicit missing values, and address device-specific quirks such as the `Clouclip`’s use of sentinel codes for “sleep mode” and “out of range” readings. Special procedures for processing the `VEET`’s rich spectral data (e.g. normalizing sensor counts and reconstructing full spectra from multiple sensor channels) are also outlined. Finally, we show how to save the cleaned datasets from both devices into a single R data file for downstream analysis. This comprehensive walkthrough is designed to ensure reproducibility and to assist researchers in understanding and adapting the data pipeline for their own visual experience datasets.\n\n## Introduction\n\nWearable sensors like the `Clouclip` and the Visual Environment Evaluation Tool (`VEET`) produce high-dimensional time-series data on viewing distance and light exposure. Proper handling of these raw data is essential before any analysis of visual experience metrics. In the [main tutorial](index.qmd), we introduce an analysis pipeline using the open-source R package LightLogR [@Zauner2025JOpenSourceSoftw] to calculate various distance and light exposure metrics. Here, we present a full account of the data import and preparation steps as a supplement to the methods, with an emphasis on clarity for researchers who may be less familiar with data processing in R.\n\nWe use example datasets from a `Clouclip` device [@Wen2021ActaOphtalmol; @Wen2020bjophthalmol] and from a `VEET` device [@Sah2025OphtalmicPhysiolOpt] (both provided in the accompanying [repository](https://github.com/tscnlab/ZaunerEtAl_JVis_2026)). The `Clouclip` is a glasses-mounted sensor that records working distance (distance from eyes to object, in cm) and ambient illuminance (in lux) at 5-second intervals. The `VEET` is a head-mounted multi-modal sensor that logs ambient light and spectral information (along with other data like motion and distance via a depth sensor) - in this exemplary case at 2-second intervals. A single week of continuous data illustrates the contrast in complexity: approximately 1.6 MB for the `Clouclip`’s simple two-column output versus up to 270 MB for the `VEET`’s multi-channel output (due to its higher sampling rate and richer sensor modalities).\n\nIn the following sections, we detail how these raw data are structured and how to import and preprocess them using LightLogR. We cover device-specific considerations such as file format quirks and sensor range limitations, as well as general best practices like handling missing timestamps and normalizing sensor readings. All code blocks can be executed in R (with the required packages loaded) to reproduce the cleaning steps. The end result will be clean, regularized datasets (`dataCC` for Clouclip, `dataVEET` for VEET light data, `dataVEET2` for VEET spectral data, and `dataVEET3` for VEET distance) ready for calculating visual experience metrics. We conclude by saving these cleaned datasets into a single file for convenient reuse.\n\n## `Clouclip` Data: Raw Structure and Import\n\nThe `Clouclip` device exports its data as a text file (not a true Excel file despite sometimes using an .xls extension), which is actually tab-separated values. See @fig-Clouclip_file for the raw file.\n\n![Screenshot of the first rows of the `Clouclip` export file format as seen in a text editor](assets/Clouclip_fileformat.png){#fig-Clouclip_file width=35%}\n\nEach record corresponds to one timestamped observation (nominally every 5 seconds) and includes two measured variables: **distance** and **illuminance**. In the sample dataset (`Sample_Clouclip.csv` provided), the columns are:\n\n-   `Date` – the date and time of the observation (in the device’s local time, here one week in 2021).\n\n-   `Dis` – the viewing distance in centimeters.\n\n-   `Lux` – the ambient illuminance in lux.\n\nFor example, a raw data line might look like:\n\n```         \n2021-07-01 08:00:00 45  320\n```\n\nindicating that at *2021-07-01 08:00:00* local time, the device recorded a working distance of 45 cm and illuminance of 320 lx. The Clouclip uses special **sentinel values**[^1] in these measurement columns to denote certain device states. Specifically, a distance (`Dis`) value of **204** is a code meaning the object is *out of the sensor’s range*, and a value of **-1** in either `Dis` or `Lux` indicates the device was in *sleep mode* (not actively recording). During normal operation, distance measurements are limited by the device’s range, and illuminance readings are positive lux values. Any sentinel codes in the raw file need to be handled appropriately, as described below.\n\n[^1]: A *sentinel value* is a special placeholder value used in data recording to signal a particular condition. It does not represent a valid measured quantity but rather acts as a marker (for example, “device off” or “value out of range”).\n\nWe will use `LightLogR`’s built-in import function for `Clouclip`, which automatically reads the file, parses the timestamps, and converts sentinel codes into a separate status annotation. To begin, we load the necessary libraries and import the raw `Clouclip` dataset:\n\n\n::: {.cell filename='Load required packages'}\n\n```{.r .cell-code}\nlibrary(tidyverse) #<1>\nlibrary(LightLogR) #<2>\nlibrary(gt) #<3>\nlibrary(ggridges) #<4>\nlibrary(downlit) #<5>\n```\n:::\n\n\n1. for tidy data science\n2. wearable analysis package\n3. for great tables\n4. for ridgeline plots\n5. this package is not used, but needs to be loaded for code-link feature in the html file\n\n\n::: {.cell filename='Import of Clouclip data'}\n\n```{.r .cell-code}\npath <- \"data/Sample_Clouclip.csv\" #<1>\ntz   <- \"US/Central\"   #<2>\ndataCC <- import$Clouclip(path, tz = tz, manual.id = \"Clouclip\") #<3>\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSuccessfully read in 58'081 observations across 1 Ids from 1 Clouclip-file(s).\nTimezone set is US/Central.\nThe system timezone is Europe/Berlin. Please correct if necessary!\n\nFirst Observation: 2021-02-06 17:12:47\nLast Observation: 2021-02-14 17:12:36\nTimespan: 8 days\n\nObservation intervals: \n  Id       interval.time            n pct     \n1 Clouclip 5s                   54572 93.9601%\n2 Clouclip 17s                     12 0.0207% \n3 Clouclip 18s                     14 0.0241% \n4 Clouclip 120s (~2 minutes)     3479 5.9900% \n5 Clouclip 128s (~2.13 minutes)     1 0.0017% \n6 Clouclip 132s (~2.2 minutes)      1 0.0017% \n7 Clouclip 133s (~2.22 minutes)     1 0.0017% \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Overview plot of imported Clouclip data](supplement_files/figure-html/fig-importCC-1.png){#fig-importCC width=576}\n:::\n:::\n\n\n1. Define file path\n2. Time zone in which device was recording (e.g., US Central Time)\n3. Import Clouclip data\n\nIn this code, `import$Clouclip()` reads the tab-delimited file and returns a **tibble**[^2] (saved in the variable `dataCC`) containing the data. We specify `tz = \"US/Central\"` because the device’s clock was set to U.S. Central time; this ensures that the `Datetime`values are properly interpreted with the correct time zone. The argument `manual.id = \"Clouclip\"` simply tags the dataset with an identifier (useful if combining data from multiple devices).\n\n[^2]: **tibble** are data.tables with tweaked behavior, ideal for a tidy analysis workflow. For more information, visit the documentation page for [tibbles](https://tibble.tidyverse.org/index.html)\n\nDuring import, LightLogR automatically handles the `Clouclip`’s sentinel codes. The `Date` column from the raw file is parsed into a `POSIXct` date-time (`Datetime`) with the specified time zone. The `Lux` and `Dis` columns are read as numeric, but any occurrences of **-1** or **204** are treated specially: these are replaced with `NA` (missing values) in the numeric columns, and corresponding status columns `Lux_status` and `Dis_status` are created to indicate the reason for those `NA` values. For example, if a `Dis` value of *204* was encountered, that row’s `Dis` will be set to NA and `Dis_status` will contain `\"out_of_range\"`; if `Lux` or `Dis` was -1, the status is `\"sleep_mode\"`. We will set all other readings to  `\"operational\"` (meaning the device was functioning normally at that time) for visualisation purposes.\n\n\n::: {.cell filename='Print the first 6 rows of the Clouclip dataset'}\n\n```{.r .cell-code}\ndataCC |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n# Groups:   Id [1]\n  Id       file.name       Datetime              Dis   Lux Lux_status Dis_status\n  <fct>    <chr>           <dttm>              <dbl> <dbl> <chr>      <chr>     \n1 Clouclip Sample_Clouclip 2021-02-06 17:12:47    92    92 <NA>       <NA>      \n2 Clouclip Sample_Clouclip 2021-02-06 17:12:52    92    92 <NA>       <NA>      \n3 Clouclip Sample_Clouclip 2021-02-06 17:12:57    92    92 <NA>       <NA>      \n4 Clouclip Sample_Clouclip 2021-02-06 17:13:02    92    92 <NA>       <NA>      \n5 Clouclip Sample_Clouclip 2021-02-06 17:13:07    92    92 <NA>       <NA>      \n6 Clouclip Sample_Clouclip 2021-02-06 17:13:12    92    92 <NA>       <NA>      \n```\n\n\n:::\n:::\n\n\n\nAfter import, it is good practice to get an overview of the data. The import function by default prints a brief summary (and generates an overview plot of the timeline) showing the number of observations, the time span, and any irregularities or large gaps. In our case, the `Clouclip` summary indicates the data spans one week and reveals that there are **irregular intervals** in the timestamps. This means some observations do not occur exactly every 5 seconds as expected. We can programmatically check for irregular timing:\n\n\n::: {.cell filename='Check if data are on a perfectly regular 5-second schedule'}\n\n```{.r .cell-code}\ndataCC |> has_irregulars()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nIf the result is `TRUE`, it confirms that the time sequence has deviations from the regular interval. Indeed, our example dataset has many small timing irregularities and gaps (periods with no data). Understanding the pattern of these missing or irregular readings is important. We can visualize them using a gap plot:\n\n\n::: {.cell filename='Plot gaps and irregular timestamps for Clouclip data'}\n\n```{.r .cell-code}\ny.label <- \"Distance (cm)\"\ndataCC |> gg_gaps(Dis, #<1>\n                  include.implicit.gaps = FALSE,  #<2>\n                  show.irregulars = TRUE,         #<3>\n                  y.axis.label = y.label,\n                  group.by.days = TRUE, col.irregular = alpha(\"red\", 0.03)\n                  ) + labs(title = NULL)\n```\n\n::: {.cell-output-display}\n![Visualization of gaps and irregular data. Black traces show available data. Red shaded areas show times of missing data. Red dots show instances where observations occur off the regular interval from start to finish, i.e., irregular data.](supplement_files/figure-html/fig-irregular-1.png){#fig-irregular width=672}\n:::\n:::\n\n\n1. Basing the gap-figure on the `Dis` distance variable\n2. Only show missing observations (`NA` values)\n3. Highlight irregular timing\n\nIn @fig-irregular, time periods where data are missing appear as red-shaded areas, and any off-schedule observation times are marked with red dots. The `Clouclip` example shows extensive gaps (red blocks) on certain days and irregular timing on all days except the first and last. These irregular timestamps likely arise from the device’s logging process (e.g. slight clock drift or buffering when the device was turned on/off). Such issues must be addressed before further analysis.\n\nWhen faced with irregular or gapped data, we recommend a few strategies:\n\n-   *Remove leading/trailing segments that cause irregularity.* For example, if only the first day is regular and subsequent days drift, one might exclude the problematic portion using date filters (see [filter_Date() / filter_Datetime()](https://tscnlab.github.io/LightLogR/reference/filter_Datetime.html) in LightLogR).\n\n-   *Round timestamps to the nearest regular interval.* This relabels slightly off-schedule times back to the 5-second grid (using [cut_Datetime()](https://tscnlab.github.io/LightLogR/reference/cut_Datetime.html) with a 5-second interval), provided the deviations are small and this rounding won’t create duplicate timestamps.\n\n-   *Aggregate to a coarser time interval.* For instance, grouping and averaging data into 1-minute bins with [aggregate_Datetime()](https://tscnlab.github.io/LightLogR/reference/aggregate_Datetime.html) can mask irregularities at finer scales, at the cost of some temporal resolution.\n\nIn this case, the deviations from the 5-second schedule are relatively minor. We choose to **round the timestamps to the nearest 5 seconds** to enforce a uniform sampling grid, which simplifies downstream gap handling. We further add a separate date column for convenience:\n\n\n::: {.cell filename='Regularize timestamps by rounding to nearest 5-second interval'}\n\n```{.r .cell-code}\ndataCC <- dataCC |>\n  cut_Datetime(\"5 secs\", New.colname = Datetime) |>  #<1>\n  add_Date_col(group.by = TRUE)                     #<2>\n```\n:::\n\n\n1. Round times to 5-second bins\n2. Add a Date column for grouping by day\n\nAfter this operation, all `Datetime` entries in `dataCC` align perfectly on 5-second boundaries (e.g. **08:00:00**, **08:00:05**, **08:00:10**, etc.). We can verify that no irregular intervals remain by re-running `has_irregulars()`:\n\n\n::: {.cell filename='Re-check if data are on a perfectly regular 5-second schedule'}\n\n```{.r .cell-code}\ndataCC |> has_irregulars()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\nNext, we want to quantify the missing data. LightLogR distinguishes between **explicit missing values** (actual `NA`s in the data, possibly from sentinel replacements or gaps we have filled in) and **implicit missing intervals** (time points where the device *should* have a reading but none was recorded, and we have not yet filled them in). See @fig-gaps for a visual aid to these terms. Initially, many gaps are still implicit (between the first and last timestamp of each day). \n\n::: {#fig-gaps layout-ncol=2}\n\n![Terminology of gaps and irregular data in LightLogR](assets/gap_terminology.png)\n\n![Handling of gaps with LightLogR's `gap_handler()` function](assets/gap_handler.png)\n\nGaps and irregular data\n\n:::\n\nWe can generate a gap summary table:\n\n\n::: {#tbl-gaps .cell tbl-cap='Summary of missing and observed data for the Clouclip device' filename='Summarize observed vs missing data by day for distance'}\n\n```{.r .cell-code}\ndataCC |> gap_table(Dis, Variable.label = \"Distance (cm)\") |>\n  cols_hide(contains(\"_n\"))   #<1>\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cqxmquvfgz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cqxmquvfgz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cqxmquvfgz thead, #cqxmquvfgz tbody, #cqxmquvfgz tfoot, #cqxmquvfgz tr, #cqxmquvfgz td, #cqxmquvfgz th {\n  border-style: none;\n}\n\n#cqxmquvfgz p {\n  margin: 0;\n  padding: 0;\n}\n\n#cqxmquvfgz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cqxmquvfgz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cqxmquvfgz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cqxmquvfgz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cqxmquvfgz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cqxmquvfgz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cqxmquvfgz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cqxmquvfgz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cqxmquvfgz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cqxmquvfgz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cqxmquvfgz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cqxmquvfgz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cqxmquvfgz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cqxmquvfgz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cqxmquvfgz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqxmquvfgz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cqxmquvfgz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cqxmquvfgz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cqxmquvfgz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqxmquvfgz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cqxmquvfgz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqxmquvfgz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cqxmquvfgz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqxmquvfgz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cqxmquvfgz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqxmquvfgz .gt_left {\n  text-align: left;\n}\n\n#cqxmquvfgz .gt_center {\n  text-align: center;\n}\n\n#cqxmquvfgz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cqxmquvfgz .gt_font_normal {\n  font-weight: normal;\n}\n\n#cqxmquvfgz .gt_font_bold {\n  font-weight: bold;\n}\n\n#cqxmquvfgz .gt_font_italic {\n  font-style: italic;\n}\n\n#cqxmquvfgz .gt_super {\n  font-size: 65%;\n}\n\n#cqxmquvfgz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cqxmquvfgz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cqxmquvfgz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cqxmquvfgz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cqxmquvfgz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cqxmquvfgz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cqxmquvfgz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cqxmquvfgz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cqxmquvfgz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"14\" class=\"gt_heading gt_title gt_font_normal\" style>Summary of available and missing data</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"14\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Variable: Distance (cm)</td>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"5\" style=\"font-weight: bold; font-weight: bold;\" scope=\"colgroup\" id=\"data_spanner\">\n        <div class=\"gt_column_spanner\">Data</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"8\" style=\"font-weight: bold; font-weight: bold;\" scope=\"colgroup\" id=\"missing_spanner\">\n        <div class=\"gt_column_spanner\">Missing</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"Regular\">\n        <div class=\"gt_column_spanner\">Regular</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"irregular_spanner\">\n        <div class=\"gt_column_spanner\">Irregular</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Range\">\n        <div class=\"gt_column_spanner\">Range</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"interval_spanner\">\n        <div class=\"gt_column_spanner\">Interval</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"gap_spanner\">\n        <div class=\"gt_column_spanner\">Gaps</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"implicit_spanner\">\n        <div class=\"gt_column_spanner\">Implicit</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"explicit_spanner\">\n        <div class=\"gt_column_spanner\">Explicit</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"available_data\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"available_data_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number_irregulars\">n<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1,2</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_duration\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interval\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number_gaps\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_gap_duration\">ø</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_data\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_data_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_implicit\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_implicit_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_explicit\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_explicit_pct\">%</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"grand_summary_stub_1\" scope=\"row\" class=\"gt_row gt_left gt_stub gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\"><span data-qmd-base64=\"KipPdmVyYWxsKio=\"><span class='gt_from_md'><strong>Overall</strong></span></span></th>\n<td headers=\"grand_summary_stub_1 available_data\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">2d 14h 43m 10s</td>\n<td headers=\"grand_summary_stub_1 available_data_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">29.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 number_irregulars\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"grand_summary_stub_1 total_duration\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1w 2d</td>\n<td headers=\"grand_summary_stub_1 interval\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5</td>\n<td headers=\"grand_summary_stub_1 number_gaps\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">2,690</td>\n<td headers=\"grand_summary_stub_1 mean_gap_duration\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">1h 35m 57s</td>\n<td headers=\"grand_summary_stub_1 missing_data\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">6d 9h 16m 50s</td>\n<td headers=\"grand_summary_stub_1 missing_data_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">71.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 missing_implicit\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5d 15h 19m 55s</td>\n<td headers=\"grand_summary_stub_1 missing_implicit_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">62.7%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 missing_explicit\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">17h 56m 55s</td>\n<td headers=\"grand_summary_stub_1 missing_explicit_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">8.3%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-06\">Clouclip - 2021-02-06</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 available_data\" class=\"gt_row gt_center\">43m 30s</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 available_data_pct\" class=\"gt_row gt_right\">3.0%</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">26</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 mean_gap_duration\" class=\"gt_row gt_right\">53m 43s</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 missing_data\" class=\"gt_row gt_center\">23h 16m 30s</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 missing_data_pct\" class=\"gt_row gt_right\">97.0%</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">22h 53m 20s</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 missing_implicit_pct\" class=\"gt_row gt_right\">95.4%</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">23m 10s</td>\n<td headers=\"Clouclip - 2021-02-06 stub_1_1 missing_explicit_pct\" class=\"gt_row gt_right\">1.6%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-07\">Clouclip - 2021-02-07</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 available_data\" class=\"gt_row gt_center\">2h 45m</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 available_data_pct\" class=\"gt_row gt_right\">11.5%</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">139</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 mean_gap_duration\" class=\"gt_row gt_right\">9m 10s</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 missing_data\" class=\"gt_row gt_center\">21h 15m</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 missing_data_pct\" class=\"gt_row gt_right\">88.5%</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">19h 42m 35s</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 missing_implicit_pct\" class=\"gt_row gt_right\">82.1%</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1h 32m 25s</td>\n<td headers=\"Clouclip - 2021-02-07 stub_1_2 missing_explicit_pct\" class=\"gt_row gt_right\">6.4%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-08\">Clouclip - 2021-02-08</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 available_data\" class=\"gt_row gt_center\">11h 13m 55s</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 available_data_pct\" class=\"gt_row gt_right\">46.8%</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">443</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 mean_gap_duration\" class=\"gt_row gt_right\">1m 44s</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 missing_data\" class=\"gt_row gt_center\">12h 46m 5s</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 missing_data_pct\" class=\"gt_row gt_right\">53.2%</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">10h 47m 50s</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 missing_implicit_pct\" class=\"gt_row gt_right\">45.0%</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1h 58m 15s</td>\n<td headers=\"Clouclip - 2021-02-08 stub_1_3 missing_explicit_pct\" class=\"gt_row gt_right\">8.2%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-09\">Clouclip - 2021-02-09</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 available_data\" class=\"gt_row gt_center\">8h 46m 25s</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 available_data_pct\" class=\"gt_row gt_right\">36.6%</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">278</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 mean_gap_duration\" class=\"gt_row gt_right\">3m 17s</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 missing_data\" class=\"gt_row gt_center\">15h 13m 35s</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 missing_data_pct\" class=\"gt_row gt_right\">63.4%</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">13h 50m</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 missing_implicit_pct\" class=\"gt_row gt_right\">57.6%</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1h 23m 35s</td>\n<td headers=\"Clouclip - 2021-02-09 stub_1_4 missing_explicit_pct\" class=\"gt_row gt_right\">5.8%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-10\">Clouclip - 2021-02-10</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 available_data\" class=\"gt_row gt_center\">7h 1m 30s</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 available_data_pct\" class=\"gt_row gt_right\">29.3%</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">367</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 mean_gap_duration\" class=\"gt_row gt_right\">2m 47s</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 missing_data\" class=\"gt_row gt_center\">16h 58m 30s</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 missing_data_pct\" class=\"gt_row gt_right\">70.7%</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">14h 18m 40s</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 missing_implicit_pct\" class=\"gt_row gt_right\">59.6%</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">2h 39m 50s</td>\n<td headers=\"Clouclip - 2021-02-10 stub_1_5 missing_explicit_pct\" class=\"gt_row gt_right\">11.1%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-11\">Clouclip - 2021-02-11</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 available_data\" class=\"gt_row gt_center\">8h 31m 55s</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 available_data_pct\" class=\"gt_row gt_right\">35.5%</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">423</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 mean_gap_duration\" class=\"gt_row gt_right\">2m 12s</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 missing_data\" class=\"gt_row gt_center\">15h 28m 5s</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 missing_data_pct\" class=\"gt_row gt_right\">64.5%</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">11h 43m 30s</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 missing_implicit_pct\" class=\"gt_row gt_right\">48.9%</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">3h 44m 35s</td>\n<td headers=\"Clouclip - 2021-02-11 stub_1_6 missing_explicit_pct\" class=\"gt_row gt_right\">15.6%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-12\">Clouclip - 2021-02-12</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 available_data\" class=\"gt_row gt_center\">12h 17m 55s</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 available_data_pct\" class=\"gt_row gt_right\">51.2%</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">417</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 mean_gap_duration\" class=\"gt_row gt_right\">1m 41s</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 missing_data\" class=\"gt_row gt_center\">11h 42m 5s</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 missing_data_pct\" class=\"gt_row gt_right\">48.8%</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">9h 17m 45s</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 missing_implicit_pct\" class=\"gt_row gt_right\">38.7%</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">2h 24m 20s</td>\n<td headers=\"Clouclip - 2021-02-12 stub_1_7 missing_explicit_pct\" class=\"gt_row gt_right\">10.0%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-13\">Clouclip - 2021-02-13</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 available_data\" class=\"gt_row gt_center\">10h 32m 15s</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 available_data_pct\" class=\"gt_row gt_right\">43.9%</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">527</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 mean_gap_duration\" class=\"gt_row gt_right\">1m 32s</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 missing_data\" class=\"gt_row gt_center\">13h 27m 45s</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 missing_data_pct\" class=\"gt_row gt_right\">56.1%</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">10h 42m 10s</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 missing_implicit_pct\" class=\"gt_row gt_right\">44.6%</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">2h 45m 35s</td>\n<td headers=\"Clouclip - 2021-02-13 stub_1_8 missing_explicit_pct\" class=\"gt_row gt_right\">11.5%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Clouclip - 2021-02-14\">Clouclip - 2021-02-14</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_9\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 available_data\" class=\"gt_row gt_center\">50m 45s</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 available_data_pct\" class=\"gt_row gt_right\">3.5%</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">70</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 mean_gap_duration\" class=\"gt_row gt_right\">19m 51s</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 missing_data\" class=\"gt_row gt_center\">23h 9m 15s</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 missing_data_pct\" class=\"gt_row gt_right\">96.5%</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">22h 4m 5s</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 missing_implicit_pct\" class=\"gt_row gt_right\">92.0%</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1h 5m 10s</td>\n<td headers=\"Clouclip - 2021-02-14 stub_1_9 missing_explicit_pct\" class=\"gt_row gt_right\">4.5%</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> If n &gt; 0: it is possible that the other summary statistics are affected, as they are calculated based on the most prominent interval.</td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> Number of (missing or actual) observations</td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span> Based on times, not necessarily number of observations</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n1. Hide absolute counts for brevity in output\n\nThis summary (@tbl-gaps) breaks down, for each day, how much data is present vs. missing. It reports the total duration of recorded data and the duration of gaps. After rounding the times, there are no irregular timestamp issues, but we see substantial **implicit gaps** — periods where the device was not recording (e.g., overnight when the device was likely not worn or was in sleep mode). Notably, the first and last days of the week have very little data (less than 1 hour each), since they probably represent partial recording days (the trial started and ended on those days).\n\nTo prepare the dataset for analysis, we will convert all those implicit gaps into explicit missing entries, and remove days that are mostly incomplete. Converting implicit gaps means inserting rows with `NA` for each missing 5-second slot, so that the time series becomes continuous and explicit about missingness (see @fig-gaps). We use `gap_handler()` for this, and then drop the nearly-empty days:\n\n\n::: {.cell filename='Convert implicit gaps to explicit NA gaps, and drop days with <1 hour of data'}\n\n```{.r .cell-code}\ndataCC <- dataCC |> \n  mutate(across(c(Lux_status, Dis_status), ~ replace_na(.x, \"operational\"))) |> #<1>\n  gap_handler(full.days = TRUE) |> #<2> \n  remove_partial_data(Dis, threshold.missing = \"-1 hour\") #<3>\n```\n:::\n\n\n1. First ensure that status columns have an \"operational\" tag for non-missing periods\n2. Fill in all implicit gaps with explicit NA rows (for full days range)\n3. Remove any day that has less than 1 hour of recorded data\n\nAfter these steps, `dataCC` contains continuous 5-second timestamps for each day that remains. We chose a threshold of “-1 hours” to remove days with less than one hour of data, which in this dataset removes the first and last (partial) days. The cleaned `Clouclip` data now covers six full days with bouts of continuous wear.\n\nIt is often helpful to double-check how the sentinel values and missing data are distributed over time. We can visualize the distance time-series with status annotations and day/night periods:\n\n\n::: {.cell filename='Visualize observations and sentinel states'}\n\n```{.r .cell-code}\ncoordinates <- c(29.75, -95.36) #<1>\ndataCC |> \n  fill(c(Lux_status, Dis_status), .direction = \"downup\") |> #<2>\n  gg_day(y.axis = Dis, geom = \"line\", y.axis.label = y.label) |> #<3>\n  gg_state(Dis_status, aes_fill = Dis_status, ymin = 0, ymax = 0.5, alpha = 1) |> #<4>\n  gg_photoperiod(coordinates, alpha = 0.1) + #<5>\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Distance measurements across days. Blue, grey and yellow-colored bars at the bottom of each day show sentinel states of the device. Blue indicates an operational status, grey sleep mode (not recording), and yellow an out of range measurement. Shaded areas in the main plot show nighttime from civil dusk until dawn, which are calculated based on the recording date and geographic coordinates](supplement_files/figure-html/fig-state-1.png){#fig-state width=672}\n:::\n:::\n\n\n1. Setting coordinates for Houston, Texas (recording location)\n2. Retain status markers until a new marker arrives\n3. Create the basic plot\n4. Add the status times\n5. Add the photoperiod (day/night)\n\nIn this plot, blue segments indicate times when the Clouclip was *operational* (actively measuring), grey segments indicate the device in *sleep mode* (no recording, typically at night), and yellow segments indicate *out-of-range* distance readings. The red outlined regions show nighttime (from civil dusk to dawn) based on the given latitude/longitude and dates. As expected, most of the grey “sleep” periods align with night hours, and we see a few yellow spans when the user’s viewing distance exceeded the device’s range (e.g. presumably when no object was within 100 cm, such as when the user looked into the distance). At this stage, the Clouclip dataset `dataCC` is fully preprocessed: all timestamps are regular 5-second intervals, missing data are explicitly marked, extraneous partial days are removed, and sentinel codes are handled via the status columns. The data are ready for calculating daily distance and light exposure metrics (as done in the [main tutorial](index.qmd)’s Results).\n\n## `VEET` Data: Ambient Light (Illuminance) Processing\n\nThe **VEET** device [@Sah2025OphtalmicPhysiolOpt, @Sullivan2024] is a more complex logger that records multiple data modalities in one combined file. Its raw data file contains interleaved records for different sensor types, distinguished by a “modality” field. We focus first on the ambient light sensor modality (abbreviated **ALS**), which provides broad-spectrum illuminance readings (lux) and related information like sensor gains and flicker, recorded every 2 seconds. Later we will import the spectral sensor modality (**PHO**) for spectral irradiance data, and the time-of-flight modality (**TOF**) for distance data.\n\nIn the `VEET`’s export file, each line includes a timestamp and a modality code, followed by fields specific to that modality. Importantly, this means that the `VEET` export is not rectangular, i.e., tabular (see @fig-VEET_file). This makes it challenging for many import functions that expect the equal number of columns in every row, which is not the case in this instance. For the **ALS modality**, the relevant columns include a high-resolution timestamp (in Unix epoch format), integration time, UV/VIS/IR sensor gain settings, raw UV/VIS/IR sensor counts, a flicker measurement, and the computed illuminance in lux. For example, the ALS data columns are named: `time_stamp`, `integration_time`, `uvGain`, `visGain`, `irGain`, `uvValue`, `visValue`, `irValue`, `Flicker`, and `Lux`.\n\n![Screenshot of the first rows of the `VEET` export file format as seen in a text editor](assets/VEET_fileformat.png){#fig-VEET_file}\n\nFor the **PHO (spectral) modality**, the columns include a timestamp, integration time, a general `Gain` factor, and nine sensor channel readings covering different wavelengths (with names like `s415, s445, ..., s680, s940`) as well as a `Dark` channel and a broadband channel `Clear`. In essence, the `VEET`’s spectral sensor captures light in several wavelength bands (from \\~415 nm up to 940 nm, plus an infrared and “clear” channel) rather than outputting a single lux value like the ambient light sensor does (*PHO*).\n\nTo import the `VEET` ambient light data, we again use the LightLogR import function, specifying the `ALS` modality. The raw VEET data in our example is provided as a zip file (`01_VEET_L.csv.zip`) containing the logged data for one week. We do the following:\n\n\n::: {.cell filename='Import VEET Ambient Light Sensor (ALS) data'}\n\n```{.r .cell-code}\npath <- \"data/01_VEET_L.csv.zip\"\ntz   <- \"US/Central\"\ndataVEET <- import$VEET(path, tz = tz, modality = \"ALS\", manual.id = \"VEET\") #<1>\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSuccessfully read in 304'193 observations across 1 Ids from 1 VEET-file(s).\nTimezone set is US/Central.\nThe system timezone is Europe/Berlin. Please correct if necessary!\n1 observations were dropped due to a missing or non-parseable Datetime value (e.g., non-valid timestamps during DST jumps). \n\nFirst Observation: 2024-06-04 15:00:37\nLast Observation: 2024-06-12 08:29:43\nTimespan: 7.7 days\n\nObservation intervals: \n  Id    interval.time              n pct      \n1 VEET  0s                         1 0.00033% \n2 VEET  1s                      1957 0.64334% \n3 VEET  2s                    300147 98.67025%\n4 VEET  3s                      2074 0.68181% \n5 VEET  4s                         3 0.00099% \n6 VEET  9s                         5 0.00164% \n7 VEET  10s                        3 0.00099% \n8 VEET  109s (~1.82 minutes)       1 0.00033% \n9 VEET  59077s (~16.41 hours)      1 0.00033% \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Overview plot of imported VEET data](supplement_files/figure-html/fig-VEET-overview-1.png){#fig-VEET-overview width=576}\n:::\n:::\n\n\n1. In difference to the `Clouclip` file, we simply respecify the device type with `import$VEET(...)`, but must also provide a `modality` argument.\n\n::: {.callout-note}\n\nWe get one warning as a single time stamp could not be parsed into a datetime - with \\~300k observations, this is not an issue.\n\n:::\n\nThis call reads in only the lines corresponding to the `ALS` modality from the `VEET` file. The result `dataVEET` is a tibble[^2] with columns such as `Datetime` (parsed from the `time_stamp`  to POSIXct in US/Central time), `Lux` (illuminance in lux), `Flicker`, and the various sensor gains/values. Columns we don't need for our analysis, like the modality code or file name, are also included but can be ignored or removed. From the import summary, we learn that the `VEET` light data, like the `Clouclip`, also exhibits irregularities and gaps. (The device nominally records every 2 seconds, but timing may drift or pause when not worn.)\n\n\n::: {.cell filename='Print the first 6 rows of the VEETs light dataset'}\n\n```{.r .cell-code}\ndataVEET |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 14\n# Groups:   Id [1]\n  Id    Datetime            file.name     time_stamp modality integration_time\n  <fct> <dttm>              <chr>              <dbl> <chr>               <dbl>\n1 VEET  2024-06-04 15:00:37 01_VEET_L.csv 1717531237 ALS                   100\n2 VEET  2024-06-04 15:00:39 01_VEET_L.csv 1717531239 ALS                   100\n3 VEET  2024-06-04 15:00:41 01_VEET_L.csv 1717531241 ALS                   100\n4 VEET  2024-06-04 15:00:43 01_VEET_L.csv 1717531243 ALS                   100\n5 VEET  2024-06-04 15:00:45 01_VEET_L.csv 1717531245 ALS                   100\n6 VEET  2024-06-04 15:00:47 01_VEET_L.csv 1717531247 ALS                   100\n# ℹ 8 more variables: uvGain <dbl>, visGain <dbl>, irGain <dbl>, uvValue <dbl>,\n#   visValue <dbl>, irValue <dbl>, Flicker <dbl>, Lux <dbl>\n```\n\n\n:::\n:::\n\n\n\nTo make the VEET light data comparable to the Clouclip’s and to simplify analysis, we choose to **aggregate the VEET illuminance data to 5-second intervals**. This slight downsampling will both reduce data volume and remove irregularities.\n\n\n::: {.cell filename='Aggregate VEET light data to 5-second intervals and mark gaps'}\n\n```{.r .cell-code}\ndataVEET <- dataVEET |>\n  aggregate_Datetime(unit = \"5 seconds\") |>  #<1>\n  gap_handler(full.days = TRUE) |>          #<2>\n  add_Date_col(group.by = TRUE) |>          #<3>\n  remove_partial_data(Lux, threshold.missing = \"1 hour\") #<4>\n```\n:::\n\n\n1. Resample to 5-sec bins (e.g. average Lux over 2-sec readings)\n2. Fill in implicit gaps with NA rows\n3. Add Date column for daily grouping\n4. Remove participant days with more than one hour of missing data\n\nFirst, `aggregate_Datetime(unit = \"5 seconds\")` combines the high-frequency 2-second observations into 5-second slots. By default, this function will average numeric columns like `Lux` over each 5-second period (and have sensible defaults for strings or categorical data). All of these *data type handlers* can be changed with the function call. The result is that `dataVEET` now has a reading every 5 seconds (or an NA if none were present in that window). Next, `gap_handler(full.days = TRUE)` inserts explicit NA entries for any 5-second timestamp that had no data within the continuous span of the recording. Then we add a `Date` column for grouping, and finally we remove days with more than 1 hour of missing data (using a more strict criterion as we did for `Clouclip`). According to the gap summary (@tbl-gaps2), this leaves six full days of `VEET` light data with good coverage, after dropping the very incomplete start/end days.\n\nWe can inspect the missing-data summary for the `VEET` illuminance data:\n\n\n::: {#tbl-gaps2 .cell tbl-cap='Summary of missing and observed data for the VEET device, light modality'}\n\n```{.r .cell-code}\ndataVEET |> gap_table(Lux, \"Illuminance (lx)\") |> cols_hide(contains(\"_n\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ygxavwcsso\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ygxavwcsso table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ygxavwcsso thead, #ygxavwcsso tbody, #ygxavwcsso tfoot, #ygxavwcsso tr, #ygxavwcsso td, #ygxavwcsso th {\n  border-style: none;\n}\n\n#ygxavwcsso p {\n  margin: 0;\n  padding: 0;\n}\n\n#ygxavwcsso .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ygxavwcsso .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ygxavwcsso .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ygxavwcsso .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ygxavwcsso .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ygxavwcsso .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ygxavwcsso .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ygxavwcsso .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ygxavwcsso .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ygxavwcsso .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ygxavwcsso .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ygxavwcsso .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ygxavwcsso .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ygxavwcsso .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ygxavwcsso .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ygxavwcsso .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ygxavwcsso .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ygxavwcsso .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ygxavwcsso .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ygxavwcsso .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ygxavwcsso .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ygxavwcsso .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ygxavwcsso .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ygxavwcsso .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ygxavwcsso .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ygxavwcsso .gt_left {\n  text-align: left;\n}\n\n#ygxavwcsso .gt_center {\n  text-align: center;\n}\n\n#ygxavwcsso .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ygxavwcsso .gt_font_normal {\n  font-weight: normal;\n}\n\n#ygxavwcsso .gt_font_bold {\n  font-weight: bold;\n}\n\n#ygxavwcsso .gt_font_italic {\n  font-style: italic;\n}\n\n#ygxavwcsso .gt_super {\n  font-size: 65%;\n}\n\n#ygxavwcsso .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ygxavwcsso .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ygxavwcsso .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ygxavwcsso .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ygxavwcsso .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ygxavwcsso .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ygxavwcsso .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ygxavwcsso .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ygxavwcsso div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"14\" class=\"gt_heading gt_title gt_font_normal\" style>Summary of available and missing data</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"14\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Variable: Illuminance (lx)</td>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"5\" style=\"font-weight: bold; font-weight: bold;\" scope=\"colgroup\" id=\"data_spanner\">\n        <div class=\"gt_column_spanner\">Data</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"8\" style=\"font-weight: bold; font-weight: bold;\" scope=\"colgroup\" id=\"missing_spanner\">\n        <div class=\"gt_column_spanner\">Missing</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"Regular\">\n        <div class=\"gt_column_spanner\">Regular</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"irregular_spanner\">\n        <div class=\"gt_column_spanner\">Irregular</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Range\">\n        <div class=\"gt_column_spanner\">Range</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"interval_spanner\">\n        <div class=\"gt_column_spanner\">Interval</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"gap_spanner\">\n        <div class=\"gt_column_spanner\">Gaps</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"implicit_spanner\">\n        <div class=\"gt_column_spanner\">Implicit</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"explicit_spanner\">\n        <div class=\"gt_column_spanner\">Explicit</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"available_data\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"available_data_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number_irregulars\">n<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1,2</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_duration\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interval\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number_gaps\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_gap_duration\">ø</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_data\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_data_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_implicit\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_implicit_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_explicit\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_explicit_pct\">%</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"grand_summary_stub_1\" scope=\"row\" class=\"gt_row gt_left gt_stub gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\"><span data-qmd-base64=\"KipPdmVyYWxsKio=\"><span class='gt_from_md'><strong>Overall</strong></span></span></th>\n<td headers=\"grand_summary_stub_1 available_data\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">5d 23h 57m 40s</td>\n<td headers=\"grand_summary_stub_1 available_data_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">100.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 number_irregulars\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"grand_summary_stub_1 total_duration\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">6d</td>\n<td headers=\"grand_summary_stub_1 interval\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5</td>\n<td headers=\"grand_summary_stub_1 number_gaps\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">8</td>\n<td headers=\"grand_summary_stub_1 mean_gap_duration\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">58s</td>\n<td headers=\"grand_summary_stub_1 missing_data\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">2m 20s</td>\n<td headers=\"grand_summary_stub_1 missing_data_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">0.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 missing_implicit\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"grand_summary_stub_1 missing_implicit_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">0.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 missing_explicit\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">2m 20s</td>\n<td headers=\"grand_summary_stub_1 missing_explicit_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">0.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"VEET - 2024-06-06\">VEET - 2024-06-06</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"VEET - 2024-06-06 stub_1_1 available_data\" class=\"gt_row gt_center\">23h 58m 5s</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 available_data_pct\" class=\"gt_row gt_right\">99.9%</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">3</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 mean_gap_duration\" class=\"gt_row gt_right\">38s</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 missing_data\" class=\"gt_row gt_center\">1m 55s</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 missing_data_pct\" class=\"gt_row gt_right\">0.1%</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 missing_implicit_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1m 55s</td>\n<td headers=\"VEET - 2024-06-06 stub_1_1 missing_explicit_pct\" class=\"gt_row gt_right\">0.1%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"VEET - 2024-06-07\">VEET - 2024-06-07</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"VEET - 2024-06-07 stub_1_2 available_data\" class=\"gt_row gt_center\">1d</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 available_data_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 mean_gap_duration\" class=\"gt_row gt_right\">0s</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 missing_data\" class=\"gt_row gt_center\">0s</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 missing_data_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 missing_implicit_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"VEET - 2024-06-07 stub_1_2 missing_explicit_pct\" class=\"gt_row gt_right\">0.0%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"VEET - 2024-06-08\">VEET - 2024-06-08</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"VEET - 2024-06-08 stub_1_3 available_data\" class=\"gt_row gt_center\">23h 59m 55s</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 available_data_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 mean_gap_duration\" class=\"gt_row gt_right\">5s</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 missing_data\" class=\"gt_row gt_center\">5s</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 missing_data_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 missing_implicit_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-08 stub_1_3 missing_explicit_pct\" class=\"gt_row gt_right\">0.0%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"VEET - 2024-06-09\">VEET - 2024-06-09</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"VEET - 2024-06-09 stub_1_4 available_data\" class=\"gt_row gt_center\">23h 59m 50s</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 available_data_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">2</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 mean_gap_duration\" class=\"gt_row gt_right\">5s</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 missing_data\" class=\"gt_row gt_center\">10s</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 missing_data_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 missing_implicit_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">10s</td>\n<td headers=\"VEET - 2024-06-09 stub_1_4 missing_explicit_pct\" class=\"gt_row gt_right\">0.0%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"VEET - 2024-06-10\">VEET - 2024-06-10</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"VEET - 2024-06-10 stub_1_5 available_data\" class=\"gt_row gt_center\">23h 59m 55s</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 available_data_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 mean_gap_duration\" class=\"gt_row gt_right\">5s</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 missing_data\" class=\"gt_row gt_center\">5s</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 missing_data_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 missing_implicit_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-10 stub_1_5 missing_explicit_pct\" class=\"gt_row gt_right\">0.0%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"VEET - 2024-06-11\">VEET - 2024-06-11</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"VEET - 2024-06-11 stub_1_6 available_data\" class=\"gt_row gt_center\">23h 59m 55s</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 available_data_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1d</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">1</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 mean_gap_duration\" class=\"gt_row gt_right\">5s</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 missing_data\" class=\"gt_row gt_center\">5s</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 missing_data_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 missing_implicit_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5s</td>\n<td headers=\"VEET - 2024-06-11 stub_1_6 missing_explicit_pct\" class=\"gt_row gt_right\">0.0%</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> If n &gt; 0: it is possible that the other summary statistics are affected, as they are calculated based on the most prominent interval.</td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> Number of (missing or actual) observations</td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span> Based on times, not necessarily number of observations</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n@tbl-gaps2 shows, for each retained day, the total recorded duration and the duration of gaps. The `VEET` device, like the `Clouclip`, was not worn continuously 24 hours per day, so there are nightly gaps of wear time (when the device was likely off the participant), but not of recordings. After our preprocessing, any implicit gaps are represented as explicit missing intervals. The `VEET`’s time sampling was originally more frequent, but by aggregating to 5 s we have ensured a uniform timeline akin to the `Clouclip`’s.\n\nAt this point, the `dataVEET` object (for illuminance) is cleaned and ready for computing light exposure metrics. For example, one could calculate daily mean illuminance or the duration spent above certain light thresholds (e.g. “outdoor light exposure” defined as \\>1000 lx) using this dataset. Indeed, basic summary tables in the [main tutorial](index.qmd) illustrate the highly skewed nature of light exposure data and the calculation of outdoor light metrics. We will not repeat those metric calculations here in the supplement, as our focus is on data preprocessing; however, having a cleaned, gap-marked time series is crucial for those metrics to be accurate.\n\n### Identifying non-wear times\n\nNot all recorded time points of the `VEET` can be considered as `wear time`. `Non-wear` times should generally be removed from time series, if possible. There are several ways how `Non-wear` can be classified [@Zauner2025npj]:\n\n1. A device detects `non-wear` and does not record any measurements during non-wear times, or has a variable in the exported data to denote non-wear times. The `Clouclip` is an example here with the `sleep mode` sentinel state\n\n2. Record non-wear separately, e.g. with a wear-log or diary. This is easy to implement, but puts a higher burden on participants and research staff, and can be error prone: forgotten, or incorrect data entries can mis-classify wear and non-wear times. For an implementation on how to remove non-wear times based on such a log, see, e.g., this [tutorial](https://tscnlab.github.io/LightLogR_webinar/advanced_01_a_day_in_daylight-live.html).\n\n3. Instruct participants with a certain behavior when removing the device to ease automated detection of non-wear times in the data. These include putting a device in a black opaque bag, so that sensor readings for light are zero, or pressing an event button (if one exists). Up- and downsides are similar to the previous option, but the measures are usually harder to decipher in the data: when a buttonpress was forgotten, does that mess up the automated detection moving forward, which expects two presses per non-wear period (at beginning and at start). When there is zero lux during the day - was it in a black bag, or was this person just in a dark environment?\n\n4. Automated detection by an algorithm. There are several possibilities to try to classify non-wear times based on the available data from a wearable. E.g., if there is an activity tracker, that can be used to determine periods of inactivity, which could indicate non-wear. If only light data is available, the standard deviation (or coefficient of variance) of light in a moving window of a few minutes can be used to determine low variance, which also indicates inactivity. Usually a histogram of values shows a spike in those periods of inactivity.\n\nIf datasets are large enough, i.e., collect data from a long enought period, `non-wear` has a diminishing effect, at least as daily metrics of light are concerned. E.g., in a monthlong study of 39 participants from Switzerland and Malaysia, [@Biller2025] found that based on a sensitivity anaylsis up to 6 hours of data could be missing **every day**, and still the daily metrics across that month would not significantly change. This assumption only holds when non-wear times are not systematic, i.e., at the same time each day.\n\nWe will perform a simple variant of the third option, and look at the `VEET`'s `IMU` modality\n\n\n::: {.cell filename='Import VEET activity (IMU) data'}\n\n```{.r .cell-code}\npath <- \"data/01_VEET_L.csv.zip\"\ntz   <- \"US/Central\"\ndataIMU <- \n  import$VEET(path, tz = tz, modality = \"IMU\", manual.id = \"VEET\",\n              remove_duplicates = TRUE, #<1>\n              silent = TRUE) #<2>\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n15 duplicate rows were removed during import.\n```\n\n\n:::\n:::\n\n\n1. Some rows in the data are duplicated. These will be removed during import\n2. In this instance, we skip the import summary\n\nTo get a quick feeling for the data, we visualize the activity variable for the x axis in @fig-IMU\n\n\n::: {.cell filename='Plotting the IMU timeline'}\n\n```{.r .cell-code}\ndataIMU |> \n  gg_days(ax, \n          aes_col = abs(ax) < 1, \n          group = consecutive_id(abs(ax) < 1),\n          y.axis.label = \"ax\"\n          )\n```\n\n::: {.cell-output-display}\n![Timeline of the activity sensor (x direction)](supplement_files/figure-html/fig-IMU-1.png){#fig-IMU width=1344}\n:::\n:::\n\n\n`ax` seems to vary between ±10. In general, the periods of inactivity seem to lie within a band of ±1. However, simply choosing this band does not eliminate false detections during times of high movement. Some data transformations can make these more clear:\n\n\n::: {.cell filename='Plotting a transformed IMU timeline'}\n\n```{.r .cell-code}\ndataIMU |> \n  aggregate_Datetime(\n    \"5 mins\",\n    numeric.handler = sd\n  ) |> \n  pivot_longer(cols = c(ax, ay, az)) |> \n  group_by(name) |> \n  gg_days(value, \n          aes_col = value < 0.05,\n          group = consecutive_id(value < 0.05),\n          y.axis.label = \"activity axes\"\n          )\n```\n\n::: {.cell-output-display}\n![Timeline of the activity sensor (x direction) - transformed to distinguish times of low activity](supplement_files/figure-html/fig-IMU2-1.png){#fig-IMU2 width=1344}\n:::\n:::\n\n\nWhat @fig-IMU2 shows is that the 5-minute standard deviation of the activity channels (x, y, and z direction) allows a pretty stable distinction between periods of high and low activity, with a threshold of **0.05**. We can us this to create a wear column. As the choice of channel does not seem to matter much, we will use `ax`.\n\n\n::: {.cell filename='Calculating times of wear and non-wear'}\n\n```{.r .cell-code}\nwear_data <- \ndataIMU |> \n  aggregate_Datetime(\"5 mins\",numeric.handler = sd) |> #<1>\n  mutate(wear = ax > 0.05) |> #<1>\n  select(Id, Datetime, wear) |> #<1>\n  extract_states(wear) #<2>\nwear_data |> #<3>\n  ungroup(Id) |> #<3>\n  summarize_numeric(remove = c(\"start\", \"end\", \"epoch\")) |> #<3>\n  gt() #<3>\nwear_data <- wear_data |> select(Id, wear, start, end) #<2>\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nyajqzliix\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nyajqzliix table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nyajqzliix thead, #nyajqzliix tbody, #nyajqzliix tfoot, #nyajqzliix tr, #nyajqzliix td, #nyajqzliix th {\n  border-style: none;\n}\n\n#nyajqzliix p {\n  margin: 0;\n  padding: 0;\n}\n\n#nyajqzliix .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nyajqzliix .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nyajqzliix .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nyajqzliix .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nyajqzliix .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nyajqzliix .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nyajqzliix .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nyajqzliix .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nyajqzliix .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nyajqzliix .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nyajqzliix .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nyajqzliix .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nyajqzliix .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nyajqzliix .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nyajqzliix .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyajqzliix .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nyajqzliix .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nyajqzliix .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nyajqzliix .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyajqzliix .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nyajqzliix .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyajqzliix .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nyajqzliix .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyajqzliix .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nyajqzliix .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nyajqzliix .gt_left {\n  text-align: left;\n}\n\n#nyajqzliix .gt_center {\n  text-align: center;\n}\n\n#nyajqzliix .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nyajqzliix .gt_font_normal {\n  font-weight: normal;\n}\n\n#nyajqzliix .gt_font_bold {\n  font-weight: bold;\n}\n\n#nyajqzliix .gt_font_italic {\n  font-style: italic;\n}\n\n#nyajqzliix .gt_super {\n  font-size: 65%;\n}\n\n#nyajqzliix .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nyajqzliix .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nyajqzliix .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nyajqzliix .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nyajqzliix .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nyajqzliix .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nyajqzliix .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nyajqzliix .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nyajqzliix div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wear\">wear</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_duration\">mean_duration</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_duration\">total_duration</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"episodes\">episodes</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"wear\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"mean_duration\" class=\"gt_row gt_center\">11447s (~3.18 hours)</td>\n<td headers=\"total_duration\" class=\"gt_row gt_center\">366300s (~4.24 days)</td>\n<td headers=\"episodes\" class=\"gt_row gt_right\">32</td></tr>\n    <tr><td headers=\"wear\" class=\"gt_row gt_center\">TRUE</td>\n<td headers=\"mean_duration\" class=\"gt_row gt_center\">9431s (~2.62 hours)</td>\n<td headers=\"total_duration\" class=\"gt_row gt_center\">301800s (~3.49 days)</td>\n<td headers=\"episodes\" class=\"gt_row gt_right\">32</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n1. Calculation of the wear-variable\n2. Extracting the start and end times of wear and non-wear\n3. Summarizing wear and non-wear times in a table\n\nWe see that most of the recorded timespan is actually non-wear (including sleep), with an average wear time of 2.6 hours.\n\nLet's add this data to the `ALS` dataset and visualize it in @fig-nonwear\n\n\n::: {.cell filename='Plotting non-wear for light'}\n\n```{.r .cell-code}\ndataVEET <- \ndataVEET |> \n  group_by(Id) |> \n  add_states(wear_data)\n\ndataVEET |> \n  gg_days(Lux) |> \n  gg_states(wear, ymax = 0, alpha = 1, fill = \"red\")\n```\n\n::: {.cell-output-display}\n![Wear times for light data, shown as red bars](supplement_files/figure-html/fig-nonwear-1.png){#fig-nonwear width=1344}\n:::\n:::\n\n\nThis looks sensible, e.g., when we look at noon of 7 June 2024. We can remove these observations based on the `wear` column to make our summaries more valid.\n\n\n::: {.cell filename='Removing non-wear observations from light modality'}\n\n```{.r .cell-code}\ndataVEET <- dataVEET |> mutate(Lux = ifelse(wear, Lux, NA)) |> group_by(Id, Date)\n```\n:::\n\n\n## `VEET` Data: Spectral Data Processing\n\n### Import\n\nIn addition to broad-band illuminance and distance, the `VEET` provides **spectral sensor data** through its `PHO` modality. Unlike illuminance, the spectral data are not given as directly interpretable radiometric metrics but rather as raw sensor counts across multiple wavelength channels, which require conversion to reconstruct a spectral power distribution. In our analysis, spectral data allow us to compute metrics like the relative contribution of short-wavelength (blue) light versus long-wavelength light in the participant’s environment. Processing this spectral data involves several necessary steps.\n\nFirst, we import the spectral modality from a second `VEET` file. This time we need to extract the lines marked as `PHO`. We will store the spectral dataset in a separate object `dataVEET2` so as not to overwrite the `dataVEET` illuminance data in our R session:\n\n\n::: {.cell filename='Import VEET Spectral Sensor (PHO) data'}\n\n```{.r .cell-code}\npath <- \"data/02_VEET_L.csv.zip\"\ndataVEET2 <- import$VEET(path, tz = tz, modality = \"PHO\", manual.id = \"VEET\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSuccessfully read in 173'013 observations across 1 Ids from 1 VEET-file(s).\nTimezone set is US/Central.\nThe system timezone is Europe/Berlin. Please correct if necessary!\n\nFirst Observation: 2025-06-17 12:25:13\nLast Observation: 2025-06-21 22:47:01\nTimespan: 4.4 days\n\nObservation intervals: \n   Id    interval.time      n pct      \n 1 VEET  1s               417 0.24102% \n 2 VEET  2s            171837 99.32086%\n 3 VEET  3s               738 0.42656% \n 4 VEET  4s                 7 0.00405% \n 5 VEET  9s                 1 0.00058% \n 6 VEET  11s                1 0.00058% \n 7 VEET  12s                2 0.00116% \n 8 VEET  13s                4 0.00231% \n 9 VEET  15s                1 0.00058% \n10 VEET  16s                1 0.00058% \n# ℹ 3 more rows\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Overview plot of imported VEET data](supplement_files/figure-html/fig-VEET-overview2-1.png){#fig-VEET-overview2 width=576}\n:::\n:::\n\n\n\n::: {.cell filename='Print the first 6 rows of the VEETs spectral dataset'}\n\n```{.r .cell-code}\ndataVEET2 |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 18\n# Groups:   Id [1]\n  Id    Datetime            file.name time_stamp modality integration_time  Gain\n  <fct> <dttm>              <chr>          <dbl> <chr>               <dbl> <dbl>\n1 VEET  2025-06-17 12:25:13 02_VEET_… 1750181113 PHO                   100   512\n2 VEET  2025-06-17 12:25:17 02_VEET_… 1750181117 PHO                   100   512\n3 VEET  2025-06-17 12:25:19 02_VEET_… 1750181119 PHO                   100   512\n4 VEET  2025-06-17 12:25:21 02_VEET_… 1750181121 PHO                   100   512\n5 VEET  2025-06-17 12:25:23 02_VEET_… 1750181123 PHO                   100   512\n6 VEET  2025-06-17 12:25:25 02_VEET_… 1750181125 PHO                   100   512\n# ℹ 11 more variables: s415 <dbl>, s445 <dbl>, s480 <dbl>, s515 <dbl>,\n#   s555 <dbl>, s590 <dbl>, s630 <dbl>, s680 <dbl>, s910 <dbl>, Dark <dbl>,\n#   Clear <dbl>\n```\n\n\n:::\n:::\n\n\n\nAfter import, `data` contains columns for the timestamp (`Datetime`), `Gain` (the sensor gain setting), and the nine spectral sensor channels plus a clear channel. These appear as numeric columns named `s415, s445, ..., s940, Dark, Clear`. Other columns are also present but not needed for now. The spectral sensor was logging at a 2-second rate. It is informative to look at a snippet of the imported spectral data before further processing. @tbl-PHO shows three rows of `data` after import (before calibration), with some technical columns omitted for brevity:\n\n\n::: {#tbl-PHO .cell filename='Table overview of spectral sensor data' tbl-cap='Overview of the spectral sensor import from the VEET device (3 observations). Each row corresponds to a 2-second timestamp (Datetime) and shows the raw sensor readings for the spectral channels (s415–s940, Dark, Clear). All values are in arbitrary sensor units (counts). Gain values and integration_time are also relevant for each interval, depending on the downstream computation.'}\n\n```{.r .cell-code}\ndataVEET2 |> \n  slice(6000:6003) |> \n  select(-c(modality, file.name, time_stamp)) |> \n  gt() |> \n  fmt_number(s415:Clear) \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pqkkbcrncu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pqkkbcrncu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pqkkbcrncu thead, #pqkkbcrncu tbody, #pqkkbcrncu tfoot, #pqkkbcrncu tr, #pqkkbcrncu td, #pqkkbcrncu th {\n  border-style: none;\n}\n\n#pqkkbcrncu p {\n  margin: 0;\n  padding: 0;\n}\n\n#pqkkbcrncu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pqkkbcrncu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pqkkbcrncu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pqkkbcrncu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pqkkbcrncu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pqkkbcrncu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pqkkbcrncu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pqkkbcrncu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pqkkbcrncu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pqkkbcrncu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pqkkbcrncu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pqkkbcrncu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pqkkbcrncu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pqkkbcrncu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pqkkbcrncu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pqkkbcrncu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pqkkbcrncu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pqkkbcrncu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pqkkbcrncu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pqkkbcrncu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pqkkbcrncu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pqkkbcrncu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pqkkbcrncu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pqkkbcrncu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pqkkbcrncu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pqkkbcrncu .gt_left {\n  text-align: left;\n}\n\n#pqkkbcrncu .gt_center {\n  text-align: center;\n}\n\n#pqkkbcrncu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pqkkbcrncu .gt_font_normal {\n  font-weight: normal;\n}\n\n#pqkkbcrncu .gt_font_bold {\n  font-weight: bold;\n}\n\n#pqkkbcrncu .gt_font_italic {\n  font-style: italic;\n}\n\n#pqkkbcrncu .gt_super {\n  font-size: 65%;\n}\n\n#pqkkbcrncu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pqkkbcrncu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pqkkbcrncu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pqkkbcrncu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pqkkbcrncu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pqkkbcrncu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pqkkbcrncu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pqkkbcrncu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pqkkbcrncu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Datetime\">Datetime</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"integration_time\">integration_time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Gain\">Gain</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s415\">s415</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s445\">s445</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s480\">s480</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s515\">s515</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s555\">s555</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s590\">s590</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s630\">s630</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s680\">s680</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s910\">s910</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Dark\">Dark</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Clear\">Clear</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"VEET\">VEET</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"VEET  Datetime\" class=\"gt_row gt_right\">2025-06-18 00:11:22</td>\n<td headers=\"VEET  integration_time\" class=\"gt_row gt_right\">100</td>\n<td headers=\"VEET  Gain\" class=\"gt_row gt_right\">512</td>\n<td headers=\"VEET  s415\" class=\"gt_row gt_right\">20.00</td>\n<td headers=\"VEET  s445\" class=\"gt_row gt_right\">27.00</td>\n<td headers=\"VEET  s480\" class=\"gt_row gt_right\">31.00</td>\n<td headers=\"VEET  s515\" class=\"gt_row gt_right\">42.00</td>\n<td headers=\"VEET  s555\" class=\"gt_row gt_right\">47.00</td>\n<td headers=\"VEET  s590\" class=\"gt_row gt_right\">63.00</td>\n<td headers=\"VEET  s630\" class=\"gt_row gt_right\">90.00</td>\n<td headers=\"VEET  s680\" class=\"gt_row gt_right\">139.00</td>\n<td headers=\"VEET  s910\" class=\"gt_row gt_right\">756.00</td>\n<td headers=\"VEET  Dark\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"VEET  Clear\" class=\"gt_row gt_right\">534.00</td></tr>\n    <tr><td headers=\"VEET  Datetime\" class=\"gt_row gt_right\">2025-06-18 00:11:24</td>\n<td headers=\"VEET  integration_time\" class=\"gt_row gt_right\">100</td>\n<td headers=\"VEET  Gain\" class=\"gt_row gt_right\">512</td>\n<td headers=\"VEET  s415\" class=\"gt_row gt_right\">21.00</td>\n<td headers=\"VEET  s445\" class=\"gt_row gt_right\">28.00</td>\n<td headers=\"VEET  s480\" class=\"gt_row gt_right\">31.00</td>\n<td headers=\"VEET  s515\" class=\"gt_row gt_right\">41.00</td>\n<td headers=\"VEET  s555\" class=\"gt_row gt_right\">47.00</td>\n<td headers=\"VEET  s590\" class=\"gt_row gt_right\">63.00</td>\n<td headers=\"VEET  s630\" class=\"gt_row gt_right\">90.00</td>\n<td headers=\"VEET  s680\" class=\"gt_row gt_right\">140.00</td>\n<td headers=\"VEET  s910\" class=\"gt_row gt_right\">756.00</td>\n<td headers=\"VEET  Dark\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"VEET  Clear\" class=\"gt_row gt_right\">534.00</td></tr>\n    <tr><td headers=\"VEET  Datetime\" class=\"gt_row gt_right\">2025-06-18 00:11:26</td>\n<td headers=\"VEET  integration_time\" class=\"gt_row gt_right\">100</td>\n<td headers=\"VEET  Gain\" class=\"gt_row gt_right\">512</td>\n<td headers=\"VEET  s415\" class=\"gt_row gt_right\">21.00</td>\n<td headers=\"VEET  s445\" class=\"gt_row gt_right\">27.00</td>\n<td headers=\"VEET  s480\" class=\"gt_row gt_right\">31.00</td>\n<td headers=\"VEET  s515\" class=\"gt_row gt_right\">41.00</td>\n<td headers=\"VEET  s555\" class=\"gt_row gt_right\">47.00</td>\n<td headers=\"VEET  s590\" class=\"gt_row gt_right\">63.00</td>\n<td headers=\"VEET  s630\" class=\"gt_row gt_right\">90.00</td>\n<td headers=\"VEET  s680\" class=\"gt_row gt_right\">139.00</td>\n<td headers=\"VEET  s910\" class=\"gt_row gt_right\">756.00</td>\n<td headers=\"VEET  Dark\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"VEET  Clear\" class=\"gt_row gt_right\">534.00</td></tr>\n    <tr><td headers=\"VEET  Datetime\" class=\"gt_row gt_right\">2025-06-18 00:11:28</td>\n<td headers=\"VEET  integration_time\" class=\"gt_row gt_right\">100</td>\n<td headers=\"VEET  Gain\" class=\"gt_row gt_right\">512</td>\n<td headers=\"VEET  s415\" class=\"gt_row gt_right\">21.00</td>\n<td headers=\"VEET  s445\" class=\"gt_row gt_right\">27.00</td>\n<td headers=\"VEET  s480\" class=\"gt_row gt_right\">31.00</td>\n<td headers=\"VEET  s515\" class=\"gt_row gt_right\">42.00</td>\n<td headers=\"VEET  s555\" class=\"gt_row gt_right\">47.00</td>\n<td headers=\"VEET  s590\" class=\"gt_row gt_right\">63.00</td>\n<td headers=\"VEET  s630\" class=\"gt_row gt_right\">90.00</td>\n<td headers=\"VEET  s680\" class=\"gt_row gt_right\">140.00</td>\n<td headers=\"VEET  s910\" class=\"gt_row gt_right\">755.00</td>\n<td headers=\"VEET  Dark\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"VEET  Clear\" class=\"gt_row gt_right\">534.00</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Spectral calibration\n\nNow we proceed with **spectral calibration**. The `VEET`’s spectral sensor counts need to be converted to physical units (spectral irradiance) via a calibration matrix provided by the manufacturer. For this example, we assume we have a calibration matrix that maps all the channel readings to an estimated spectral power distribution (SPD). The LightLogR package provides a function `spectral_reconstruction()` to perform this conversion. However, before applying it, we must ensure the sensor counts are in a normalized form. This procedure is laid out by the manufacturer. In our version, we refer to the [*VEET SPD Reconstruction Guide.pdf*](https://projectveet.com/wp-content/uploads/VEET-Spectral-Power-Distribution-Reconstruction-Guide.pdf){target=\"_blank\"}, version *06/05/2025*. Note that each manufacturer has to specify the method of count normalization (if any) and spectral reconstruction. In our raw data, each observation comes with a `Gain` setting that indicates how the sensor’s sensitivity was adjusted; we need to divide the raw counts by the gain to get normalized counts. LightLogR offers `normalize_counts()` for this purpose. We further need to scale by integration time (in milliseconds) and adjust depending on counts in the `Dark` sensor channel.\n\n\n::: {.cell filename='Normalize spectral sensor counts'}\n\n```{.r .cell-code}\ncount.columns <- c(\"s415\", \"s445\", \"s480\", \"s515\", \"s555\", \"s590\", \"s630\", #<1>\n                      \"s680\", \"s910\", \"Dark\", \"Clear\") #<1>\n\ngain.ratios <- #<2>\n  tibble( #<2>\n    gain = c(0.5, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512), #<2>\n    gain.ratio = #<2>\n      c(0.008, 0.016, 0.032, 0.065, 0.125, 0.25, 0.5, 1, 2, 3.95, 7.75) #<2>\n  ) #<2>\n\n#normalize data:\ndataVEET2 <-\n  dataVEET2 |> \n  mutate(across(c(s415:Clear), \\(x) (x - Dark)/integration_time)) |>  #<3> \n  normalize_counts( #<4>\n    gain.columns = rep(\"Gain\", 11), #<5> \n    count.columns = count.columns, #<6>\n    gain.ratios #<7>\n  ) |> \n  select(-c(s415:Clear)) |> #<8>\n  rename_with(~ str_remove(.x, \".normalized\")) #<8>\n```\n:::\n\n\n1.  Column names of variables that need to be normalized\n2.  Gain ratios as specified by the manufacturer's reconstruction guide\n3.  Remove dark counts & scale by integration time\n4.  Function to normalize counts\n5.  All sensor channels share the gain value\n6.  Sensor channels to normalize (see 1.)\n7.  Gain ratios (see 2.)\n8.  Drop original raw count columns\n\nIn this call, we specified `gain.columns = rep(\"Gain\", 11)` because we have 11 sensor columns that all use the same gain factor column (`Gain`). This step will add new columns (with a suffix, e.g. `.normalized`) for each spectral channel representing the count normalized by the gain. We then dropped the `raw` count columns and renamed the normalized ones by dropping `.normalized` from the names. After this, `dataVEET2` contains the normalized sensor readings for `s415, s445, ..., s940, Dark, Clear` for each time point time point.\n\nBecause we do not need this high a resolution, we will **aggregate it to a 5-minute interval** for computational efficiency. The assumption is that spectral composition does not need to be examined at every 2-second instant for our purposes, and 5-minute averages can capture the general trends while drastically reducing data size and downstream computational costs.\n\n\n::: {.cell filename='Aggregate spectral data to 5-minute intervals and mark gaps'}\n\n```{.r .cell-code}\ndataVEET2 <- dataVEET2 |>\n  aggregate_Datetime(unit = \"5 mins\") |>     #<1>\n  gap_handler(full.days = TRUE) |>           #<2> \n  add_Date_col(group.by = TRUE) |>           #<3> \n  remove_partial_data(Clear, threshold.missing = \"1 hour\") #<4> \n```\n:::\n\n\n1. Aggregate to 5-minute bins\n2. Explicit NA for any gaps in between\n3. Add a date identifier for grouping\n4. remove days with more than one hour of data missing\n\nWe aggregate over 5-minute windows; within each 5-minute bin, multiple spectral readings (if present) are combined (averaged). We use one of the channels (here `Clear`) as the reference variable for `remove_partial_data` to drop incomplete days (the choice of channel is arbitrary as all channels share the same level of completeness).\n\n::: callout-warning\nPlease note that `normalize_counts()` requires the `Gain` values according to the gain table. If we had aggregated the data before normalizing it, `Gain` values would have been averaged within each bin (5 minutes in this case). If the `Gain` did not change in that time, it is not an issue. Any mix of `Gain` values will lead to a `Gain` value that is not represented in the gain table. While outputs for `normalize_counts()` are not wrong in these cases, they will output `NA` if a `Gain` value is not found in the table. Thus we recommend to always normalize counts based on the raw dataset.\n:::\n\n### Spectral reconstruction\n\nFor spectral reconstruction, we require a calibration matrix that corresponds to the `VEET`’s sensor channels. This matrix would typically be obtained from the device manufacturer or a calibration procedure. It defines how each channel’s normalized count relates to intensity at various wavelengths. For demonstration, the calibration matrix was provided by the manufacturer and is specific to the make and model (see @fig-calibmtx). It should not be used for research purposes without confirming its accuracy with the manufacturer.\n\n![Calibration matrix](assets/calibration_matrix.png){#fig-calibmtx}\n\n\n::: {.cell filename='Calibration matrica and reconstruction of spectral power distribution'}\n\n```{.r .cell-code}\ncalib_mtx <- # <1>\n  read_csv(\"data/VEET_calibration_matrix.csv\", # <1>\n           show_col_types = FALSE) |> # <1>\n  column_to_rownames(\"wavelength\") # <1>\n\ndataVEET2 <-\n  dataVEET2 |> \n  mutate(\n  Spectrum = \n    spectral_reconstruction( # <2>\n      pick(s415:s910),   # <3>\n      calibration_matrix = calib_mtx, #<4>\n      format = \"long\" # <5>\n  )\n)\n```\n:::\n\n\n1. Import the calibration matrix and make certain `wavelength` is set a rownames\n2.  The function `spectral_reconstruction()` does not work on the level of the dataset, but has to be called within `mutate()`(or provided the data directly)\n3.  Pick the normalized sensor columns\n4.  Provide the calibration matrix\n5.  Return a long-form list column (wavelength, intensity)\n\nHere, we use `format = \"long\"` so that the result for each observation is a **list-column** `Spectrum`, where each entry is a tibble[^2] containing two columns: `wavelength` and `irradiance` (one row per wavelength in the calibration matrix). In other words, each row of `dataVEET2` now holds a full reconstructed spectrum in the `Spectrum` column. The long format is convenient for further calculations and plotting. (An alternative `format = \"wide\"` would add each wavelength as a separate column, but that is less practical when there are many wavelengths.)\n\nTo visualize the data we will calculate the photopic illuminance based on the spectra and plot each spectrum color-scaled by their illuminance. For clarity, we reduce the data to observations within the day that has the most observations (non-`NA`).\n\n\n::: {.cell filename='Calculate photopic illuminance'}\n\n```{.r .cell-code}\ndata_spectra <- \ndataVEET2 |> \n  sample_groups(order.by = sum(!is.implicit)) |> #<1>\n  mutate( \n    Illuminance = Spectrum |> #<2>\n      map_dbl(spectral_integration, #<3>\n              action.spectrum = \"photopic\", #<4>\n              general.weight = \"auto\") #<5>\n  ) |> \n  unnest(Spectrum) #<6>\ndata_spectra |> select(Id, Date, Datetime, Illuminance) |> distinct()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 288 × 4\n# Groups:   Id, Date [1]\n   Id    Date       Datetime            Illuminance\n   <fct> <date>     <dttm>                    <dbl>\n 1 VEET  2025-06-18 2025-06-18 00:00:00        3.70\n 2 VEET  2025-06-18 2025-06-18 00:05:00        3.79\n 3 VEET  2025-06-18 2025-06-18 00:10:00        3.72\n 4 VEET  2025-06-18 2025-06-18 00:15:00        6.90\n 5 VEET  2025-06-18 2025-06-18 00:20:00        3.53\n 6 VEET  2025-06-18 2025-06-18 00:25:00        3.26\n 7 VEET  2025-06-18 2025-06-18 00:30:00        3.59\n 8 VEET  2025-06-18 2025-06-18 00:35:00        3.49\n 9 VEET  2025-06-18 2025-06-18 00:40:00        3.54\n10 VEET  2025-06-18 2025-06-18 00:45:00        3.62\n# ℹ 278 more rows\n```\n\n\n:::\n:::\n\n\n1.  Keep only observations for one day (with the lowest missing intervals)\n2.  Use the spectrum,...\n3.  ... call the function `spectral_integration()` for each,...\n4.  ... use the brightness sensitivity function,...\n5.  ... and apply the appropriate efficacy weight.\n6.  Create a long format of the data where the spectrum is unnested\n\nThe following plot visualizes the spectra:\n\n\n::: {.cell filename='Plot spectra'}\n\n```{.r .cell-code}\ndata_spectra |> \n  ggplot(aes(x = wavelength,group = Datetime)) +\n  geom_line(aes(y = irradiance*1000, col = Illuminance)) +\n  labs(y = \"Irradiance (mW/m²/nm)\", \n       x = \"Wavelength (nm)\", \n       col = \"Photopic illuminance (lx)\") +\n  scale_color_viridis_b(breaks = c(0, 10^(0:3))) +\n  scale_y_continuous(trans = \"symlog\", breaks = c(0, 1, 10, 50)) +\n  coord_cartesian(ylim = c(0,NA), expand = FALSE) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Overview of the reconstructed spectra, color-scaled by photopic illuminance (lx)](supplement_files/figure-html/fig-VEET-spectra-intensity-1.png){#fig-VEET-spectra-intensity width=768}\n:::\n:::\n\n\nThe following ridgeline plot can be used to assess **when** in the day certain spectral wavelenghts are dominant:\n\n\n::: {.cell filename='Plot spectra across the time of day'}\n\n```{.r .cell-code}\ndata_spectra |> \n  ggplot(aes(x = wavelength, group = Datetime)) +\n  geom_ridgeline(aes(height = irradiance*1000, \n                     y = Datetime, \n                     fill = Illuminance), \n                 scale = 400, lwd = 0.1, alpha = 0.7) +\n  labs(y = \"Local time & Irradiance (mW/m²/nm)\", \n       x = \"Wavelength (nm)\", \n       fill = \"Photopic illuminance (lx)\")+\n  scale_fill_viridis_b(breaks = c(0, 10^(0:3))) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Overview of the reconstructed spectra by time of day, color-scaled by photopic illuminance (lx)](supplement_files/figure-html/fig-VEET-spectra-time-1.png){#fig-VEET-spectra-time width=768}\n:::\n:::\n\n\n\nAt this stage, the `dataVEET2` dataset has been processed to yield time-series of spectral power distributions. We can use these to compute biologically relevant light metrics. For instance, one possible metric is the proportion of power in short wavelengths versus long wavelengths. \n\nIn the main analysis, we defined **short-wavelength (blue light) content** as the integrated intensity in the 400–500 nm range, and **long-wavelength content** as the integrated intensity in a longer range (e.g. 600–700 nm), then computed the *short-to-long ratio* (“sl ratio”). Calculating these metrics is the first step of spectrum analysis in the [main tutorial](index.qmd#spectrum).\n\n```\ndataVEET2 |> \n  select(Id, Date, Datetime, Spectrum) |>    # focus on ID, date, time, and spectrum\n  mutate(\n    short = Spectrum |> map_dbl(spectral_integration, wavelength.range = c(400, 500)),\n    long  = Spectrum |> map_dbl(spectral_integration, wavelength.range = c(600, 700)),\n    `sl ratio` = short / long   # compute short-to-long ratio\n  )\n```\n\n*(The cutoff of 500 nm here is hypothetical for demonstration; actual definitions might vary.)* We would then have columns `short`, `long`, and `sl_ratio` for each observation, which could be averaged per day or analyzed further. The cleaned spectral data in `dataVEET2` makes it straightforward to calculate such metrics or apply spectral weighting functions (for melatonin suppression, circadian stimulus, etc., if one has the spectral sensitivity curves).\n\nWith the `VEET` spectral preprocessing complete, we emphasize that these steps – normalizing by gain, applying calibration, and perhaps simplifying channels – are **device-specific** requirements. They ensure that the raw sensor counts are translated into meaningful physical measures (like spectral irradiance). Researchers using other spectral devices would follow a similar procedure, adjusting for their device’s particulars (some may output spectra directly, whereas others, like `VEET`, require reconstruction.\n\n::: {.callout-note}\n\nSome devices may output normalized counts instead of raw counts. For example, the `ActLumus` device outputs normalized counts, while the `VEET` device records raw counts and the gain. Manufacturers will be able to speficy exact outputs for a given model and software version.\n\n:::\n\n## `VEET` Data: Time of flight (distance)\n\nIn this last section, the distance data of the `VEET` device will be imported, analogous to the other modalities. The `TOF` modality contains information for up to two objects in a 8x8 grid of measurements, spanning a total of about 52° vertically and 41° horizontally. Because the `VEET` device can detect up to two objects in a given grid point, and there is a confidence value assigned to every measurement, each observation contains $2*2*8*8 = 256$ measurements.\n\n\n::: {.cell filename='Import VEET Spectral Sensor (TOF) data'}\n\n```{.r .cell-code}\npath <- \"data/01_VEET_L.csv.zip\"\ndataVEET3 <- import$VEET(path, \n                        tz = tz, \n                        modality = \"TOF\", #<1>\n                        manual.id = \"VEET\" #<2>\n                        ) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSuccessfully read in 304'195 observations across 1 Ids from 1 VEET-file(s).\nTimezone set is US/Central.\nThe system timezone is Europe/Berlin. Please correct if necessary!\n\nFirst Observation: 2024-06-04 15:00:36\nLast Observation: 2024-06-12 08:29:43\nTimespan: 7.7 days\n\nObservation intervals: \n  Id    interval.time              n pct      \n1 VEET  0s                         3 0.00099% \n2 VEET  1s                      2089 0.68673% \n3 VEET  2s                    299876 98.58051%\n4 VEET  3s                      2213 0.72750% \n5 VEET  4s                         3 0.00099% \n6 VEET  6s                         1 0.00033% \n7 VEET  9s                         7 0.00230% \n8 VEET  109s (~1.82 minutes)       1 0.00033% \n9 VEET  59077s (~16.41 hours)      1 0.00033% \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Overview plot of imported VEET data](supplement_files/figure-html/fig-VEET-overview3-1.png){#fig-VEET-overview3 width=576}\n:::\n:::\n\n\n1.  `modality` is a parameter only the `VEET` device requires. If uncertain, which devices require special parameters, have a look a the import help page (`?import`) under the `VEET` device. Setting it to `TOF` gives us the distance modality.\n2.  As we are only dealing with one individual here, we set a manual `Id`\n\n\n::: {.cell filename='Print the first 6 rows of the VEETs distance dataset'}\n\n```{.r .cell-code}\ndataVEET3 |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 261\n# Groups:   Id [1]\n  Id    Datetime            file.name     time_stamp modality conf1_0 conf1_1\n  <fct> <dttm>              <chr>              <dbl> <chr>      <dbl>   <dbl>\n1 VEET  2024-06-04 15:00:36 01_VEET_L.csv 1717531236 TOF           46      36\n2 VEET  2024-06-04 15:00:38 01_VEET_L.csv 1717531238 TOF           29      22\n3 VEET  2024-06-04 15:00:40 01_VEET_L.csv 1717531240 TOF            0       0\n4 VEET  2024-06-04 15:00:42 01_VEET_L.csv 1717531242 TOF            0       0\n5 VEET  2024-06-04 15:00:44 01_VEET_L.csv 1717531244 TOF            0       0\n6 VEET  2024-06-04 15:00:46 01_VEET_L.csv 1717531246 TOF           59      40\n# ℹ 254 more variables: conf1_2 <dbl>, conf1_3 <dbl>, conf1_4 <dbl>,\n#   conf1_5 <dbl>, conf1_6 <dbl>, conf1_7 <dbl>, conf1_8 <dbl>, conf1_9 <dbl>,\n#   conf1_10 <dbl>, conf1_11 <dbl>, conf1_12 <dbl>, conf1_13 <dbl>,\n#   conf1_14 <dbl>, conf1_15 <dbl>, conf1_16 <dbl>, conf1_17 <dbl>,\n#   conf1_18 <dbl>, conf1_19 <dbl>, conf1_20 <dbl>, conf1_21 <dbl>,\n#   conf1_22 <dbl>, conf1_23 <dbl>, conf1_24 <dbl>, conf1_25 <dbl>,\n#   conf1_26 <dbl>, conf1_27 <dbl>, conf1_28 <dbl>, conf1_29 <dbl>, …\n```\n\n\n:::\n:::\n\n\n\nIn a first step, we condition the data similarly to the other `VEET` modalities. For computational reasons of the use cases, we remove the second object and set the interval to `10 seconds`. *Note that the next step still takes considerable computation time*.\n\n\n::: {.cell filename='Aggregate distance data to 5-second intervals and mark gaps'}\n\n```{.r .cell-code}\ndataVEET3 <- \n  dataVEET3 |>\n  select(-contains(c(\"conf2_\", \"dist2_\"))) |> # <1>\n  aggregate_Datetime(unit = \"5 secs\") |>     # <2>\n  gap_handler(full.days = TRUE) |>           # <3>\n  add_Date_col(group.by = TRUE) |> \n  remove_partial_data(dist1_0, threshold.missing = \"1 hour\")\ndataVEET3 |> summary_overview(dist1_0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  name                mean   min   max\n  <chr>              <dbl> <dbl> <dbl>\n1 Participants           1    NA    NA\n2 Participant-days       6     6     6\n3 Days ≥80% complete     6     6     6\n4 Missing/Irregular      0     0     0\n```\n\n\n:::\n:::\n\n\n1.  Remove the second object (for computational reasons)\n2.  Aggregate to 10-second bins\n3.  Explicit NA for any gaps\n\nIn the next step, we need to transform the `wide` format of the imported dataset into a `long` format, where each row contains exactly one observation for one grid-point. \n\n\n::: {.cell filename='Pivot distance grid from wide to long'}\n\n```{.r .cell-code}\ndataVEET3 <- \n  dataVEET3 |> \n  pivot_longer(\n    cols = -c(Datetime, file.name, Id, is.implicit, time_stamp, modality, Date),\n    names_to = c(\".value\", \"position\"),\n    names_pattern = \"(conf1|conf2|dist1|dist2)_(\\\\d+)\"\n  )\n```\n:::\n\n\nIn a final step before we can use the data in the analysis, we need to assign `x` and `y` coordinates based on the `position` column that was created when pivoting longer. Positions are counted from 0 to 63 starting at the top right and increasing towards the left, before continuing on the right in the next row below. `y` positions thus depend on the row count, i.e., how often a row of 8 values fits into the `position` column. `x` positions consequently depend on the `position` within each 8-value row. We also add an `observation` variable that increases by `+1` every time, the `position` column hits `0`. We then center both `x` and `y` coordinates to receive meaningful values, i.e., 0° indicates the center of the overall measurement cone. Lastly, we convert both confidence columns, which are scaled from 0-255 into percentages by dividing them by `255`. Empirical data from the manufacturer points to a threshold of about `10%`, under which the respective distance data is not reliable.\n\n\n::: {.cell filename='Calculate grid positions of spatial distance measurements'}\n\n```{.r .cell-code}\ndataVEET3 <- \n  dataVEET3 |> \n  mutate(position = as.numeric(position),\n         y.pos = (position %/% 8)+1, #<1>\n         y.pos = scale(y.pos, scale = FALSE)*52/8, #<2>\n         x.pos = 8 - (position %% 8), #<3>\n         x.pos = scale(x.pos, scale = FALSE)*41/8, #<4>\n         observation = cumsum(position == 0), #<5>\n         across(starts_with(\"conf\"), \\(x) x/255) #<6>\n         )\n```\n:::\n\n\n1.  Increment the y position for every 8 steps in `position`\n2.  Center `y.pos` and rescale it to cover 52° across 8 steps\n3.  Increment the x position for every step in `position`, resetting every 8 steps\n4.  Center `x.pos` and rescale it to cover 41° across 8 steps\n5.  Increase an observation counter every time we restart with `position` at 0\n6.  Scale the confidence columns so that 255 = 100%\n\nNow this dataset is ready for further analysis. We finish by visualizing the same observation time on different days. Note that we replace zero distance values with `Infinity`, as these indicate measurements outside the 5m measurement radius of the device.\n\n\n::: {.cell filename='Plot spatial distance grid for the same time point on each day'}\n\n```{.r .cell-code}\nextras <- list( #<1>\n  geom_tile(), #<1>\n  scale_fill_viridis_c(direction = -1, limits = c(0, 200), #<1>\n                       oob = scales::oob_squish_any), #<1>\n  scale_color_manual(values = c(\"black\", \"white\")), #<1>\n  theme_minimal(), #<1>\n  guides(colour = \"none\"), #<1>\n  geom_text(aes(label = (dist1/10) |> round(0), colour = dist1>1000), #<1>\n            size = 2.5), #<1>\n  coord_fixed(), #<1>\n  labs(x = \"X position (°)\", y = \"Y position (°)\", #<1>\n       fill = \"Distance (cm)\")) #<1>\n\nslicer <- function(x){seq(min((x-1)*64+1), max(x*64, by = 1))} #<2>\n\ndataVEET3 |> \n  slice(slicer(9530)) |>  #<3>\n  mutate(dist1 = ifelse(dist1 == 0, Inf, dist1)) |> #<4>\n  filter(conf1 >= 0.1 | dist1 == Inf) |> #<5>\n  ggplot(aes(x=x.pos, y=y.pos, fill = dist1/10))+ extras + #<6>\n  facet_grid(~Datetime) #<7>\n```\n\n::: {.cell-output-display}\n![Example observations of the measurement grid at 1:14 p.m. for each measurement day. Text values show distance in cm. Empty grid points show values with low confidence. Zero-distance values were replaced with infinite distance and plotted despite low confidence.](supplement_files/figure-html/fig-VEET-distance-1.png){#fig-VEET-distance width=1152}\n:::\n:::\n\n\n1.  Set visualization parameters\n2.  Allows to choose an observation\n3.  Choose a particular observation\n4.  Replace 0 distances with Infinity\n5.  Remove data that has less than 10% confidence\n6.  Plot the data\n7.  Show one plot per day\n\nAs we can see from the figure, different days have - at a given time - a vastly different distribution of distance data, and measurement confidence (values with confidence \\< 10% are removed)\n\n### Removing non-wear times\n\nSame as for the `ALS` modality, we can remove times of non-wear - we can even use the same `wear_data` set for it:\n\n\n::: {.cell filename='Removing non-wear observations from distance modality'}\n\n```{.r .cell-code}\ndataVEET3 <- \n  dataVEET3 |> \n  group_by(Id) |> \n  add_states(wear_data)\n\ndataVEET3 <- \n  dataVEET3 |> \n  mutate(dist1 = ifelse(wear, dist1, NA)) |> \n  group_by(Id, Date)\n```\n:::\n\n\n\n## Saving the Cleaned Data\n\nAfter executing all the above steps, we have three cleaned data frames in our R session:\n\n-   **`dataCC`** – the processed `Clouclip` dataset (5-second intervals, with distance and lux, including NA for gaps and sentinel statuses).\n\n-   **`dataVEET`** – the processed `VEET` ambient light dataset (5-second intervals, illuminance in lux, with gaps filled).\n\n-   **`dataVEET2`** – the processed `VEET` spectral dataset (5-minute intervals, each entry containing a spectrum or derived spectral metrics).\n\n-   **`dataVEET3`** – the processed `VEET` distance dataset (5-second intervals, each entry containing the distance of up to two objects in the 8x8 grid).\n\nFor convenience and future reproducibility, we will save these combined results to a single R data file. Storing all cleaned data together ensures that any analysis can reload the exact same data state without re-running the import and cleaning (which can be time-consuming for large raw files).\n\n\n::: {.cell filename='Save preprocessed files'}\n\n```{.r .cell-code}\nif (!dir.exists(\"data/cleaned\")) dir.create(\"data/cleaned\", recursive = TRUE) #<1>\nsave(dataCC, dataVEET, dataVEET2, dataVEET3, file = \"data/cleaned/data.RData\") #<2>\n```\n:::\n\n\n1. Create directory for cleaned data if it doesn't exist\n2. Save all cleaned datasets into one .RData file\n\nThe above code creates (if necessary) a folder `data/cleaned/` and saves a single RData file (`data.RData`) containing the three objects. To retrieve them later, one can use `<- load(\"data/cleaned/data.RData\")`, which will return the objects into the environment. This single-file approach simplifies sharing and keeps the cleaned data together.\n\nIn summary, this supplement has walked through the full preprocessing pipeline for two example devices. We began by describing the raw data format for each device and then demonstrated how to import the data with correct time zone settings. We handled device-specific quirks like sentinel codes (for `Clouclip`) and multiple modalities with gain normalization (for `VEET`). We showed how to detect and address irregular sampling, how to explicitly mark missing data gaps to avoid analytic pitfalls, and how to reduce data granularity via rounding or aggregation when appropriate. Throughout, we used functions from LightLogR in a tidyverse workflow, aiming to make the steps clear and modular. By saving the final cleaned datasets, we set the stage for the computation of visual experience metrics such as working distance, time in bright light, spectral composition ratios, as presented in the [main tutorial](index.qmd). We hope this detailed tutorial empowers researchers to adopt similar pipelines for their own data, facilitating reproducible and accurate analyses of visual experience.\n\n## References\n",
    "supporting": [
      "supplement_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}