---
bibliography: references.bib
---

+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| No.        | Name                                                                                   | Implementation[^1]                                                                                                 |
+============+========================================================================================+====================================================================================================================+
|            | **Distance**                                                                           |                                                                                                                    |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 1          | Total wear time daily                                                                  | [durations()](https://tscnlab.github.io/LightLogR/reference/durations.html)                                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 2          | Duration of\                                                                           | filter for distance range +                                                                                        |
|            | *Near work,\                                                                           |                                                                                                                    |
|            | Intermediate Work,\                                                                    | [durations()](https://tscnlab.github.io/LightLogR/reference/durations.html) (for single ranges)                    |
|            | Near + Intermediate Work,* or                                                          |                                                                                                                    |
|            |                                                                                        | or                                                                                                                 |
|            | per each *Distance range*\                                                             |                                                                                                                    |
|            | (10cm steps)                                                                           | grouping by distance range +                                                                                       |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | [durations()](https://tscnlab.github.io/LightLogR/reference/durations.html) (for all ranges)                       |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 3          | Frequency of\                                                                          | [extract_clusters()](https://tscnlab.github.io/LightLogR/reference/extract_clusters.html) +                        |
|            | *Continuous near work*                                                                 |                                                                                                                    |
|            |                                                                                        | [summarize_numeric()](https://tscnlab.github.io/LightLogR/reference/summarize_numeric.html)                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 4          | Frequency,\                                                                            | [extract_clusters()](https://tscnlab.github.io/LightLogR/reference/extract_clusters.html) +                        |
|            | duration,\                                                                             |                                                                                                                    |
|            | and distances of\                                                                      | [extract_metric()](https://tscnlab.github.io/LightLogR/reference/extract_metric.html) +                            |
|            | *Near Work episodes*                                                                   |                                                                                                                    |
|            |                                                                                        | [summarize_numeric()](https://tscnlab.github.io/LightLogR/reference/summarize_numeric.html)                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 5          | Frequency and duration of *Visual breaks*                                              | [extract_clusters()](https://tscnlab.github.io/LightLogR/reference/extract_clusters.html) +                        |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | filter                                                                                                             |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
|            | **Light**                                                                              |                                                                                                                    |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 6          | Light exposure (in lux)                                                                | [summarize_numeric()](https://tscnlab.github.io/LightLogR/reference/summarize_numeric.html)                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 7          | Duration per *Outdoor range*                                                           | grouping by Outdoor range +                                                                                        |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | [durations()](https://tscnlab.github.io/LightLogR/reference/durations.html)                                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 8          | The number of times light level changes from indoor (\<1000 lx) to outdoor (\>1000 lx) | [extract_states()](https://tscnlab.github.io/LightLogR/reference/extract_states.html) +                            |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | [summarize_numeric()](https://tscnlab.github.io/LightLogR/reference/summarize_numeric.html)                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 9          | Longest period above 1000 lx                                                           | [period_above_threshold()](https://tscnlab.github.io/LightLogR/reference/period_above_threshold.html)              |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
|            | **Spectrum**                                                                           |                                                                                                                    |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 10         | Ratio of short vs. long wavelength light                                               | [spectral_integration()](https://tscnlab.github.io/LightLogR/reference/spectral_integration.html) +                |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | [summarize_numeric()](https://tscnlab.github.io/LightLogR/reference/summarize_numeric.html)                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 11         | Melanopic daylight efficacy ratio (MDER)                                               | [spectral_integration()](https://tscnlab.github.io/LightLogR/reference/spectral_integration.html) +                |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | [summarize_numeric()](https://tscnlab.github.io/LightLogR/reference/summarize_numeric.html)                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| 12         | Short-wavelength light at certain times of day                                         | [spectral_integration()](https://tscnlab.github.io/LightLogR/reference/spectral_integration.html) +                |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | [filter_Time()](https://tscnlab.github.io/LightLogR/reference/filter_Time.html) (for defined times) or\            |
|            |                                                                                        | [cut_Datetime()](https://tscnlab.github.io/LightLogR/reference/cut_Datetime.html) (for regular time intervals) or\ |
|            |                                                                                        | [add_photoperiod()](https://tscnlab.github.io/LightLogR/reference/photoperiod.html) (for solar times) +            |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | grouping by time state +                                                                                           |
|            |                                                                                        |                                                                                                                    |
|            |                                                                                        | [summarize_numeric()](https://tscnlab.github.io/LightLogR/reference/summarize_numeric.html)                        |
+------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+

: Overview of metrics as they are used in this article. In all cases, the averages for weekday, weekend, and the mean daily value are calculated through [mean_daily](<https://tscnlab.github.io/LightLogR/reference/mean_daily.html>). {#tbl-one}{.hover .bordered}

[^1]: Functions from `LightLogR` are presented as links to the function documentation. General analysis functions (from package `dplyr`) are presented as normal text.
